# Generated by Django 4.2.6 on 2023-10-14 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='chat_id',
        ),
        migrations.RemoveField(
            model_name='users',
            name='telegram_user_name',
        ),
    ]
